### PR TITLE
Pull request for #33: Prevents duplicate cache

### PR DESCRIPTION
**Pull request by lboxell**

### CODE REVIEW

**Comment by yuchuan2016** [comment]
Is this only working on Mac?

**Comment by lboxell** [comment]
@yuchuan2016,

If a user specified cache directory exists, then I think it should work on PC too. The current path for the cache is mac specific, but this is something that can easily be changed by the user (and should be changed).

I don't have easy access to a PC to confirm this though. If you could test on your laptop, that would be great.

**Comment by yuchuan2016** [comment]
Thanks @lboxell ! I have two questions.
- Since you `import gslab_scons.release as release`, this would overwrite the `release` directory you defined above. Perhaps change to `release_dir`
- After I change the name, I got the error when typing `scons mode=release version=1.0`. Do you know what's wrong with this?
```
TypeError: release() got multiple values for keyword argument 'org':
  File "C:\Users\yuchu\Desktop\template\SConstruct", line 54:
    release.release(env, vers, DriveReleaseFiles, release_dir, org = 'gslab-econ', repo = 'template')
```

**Comment by lboxell** [comment]
@yuchuan2016,

I believe I've fixed the issues. We've changed release protocols (see https://github.com/gslab-econ/template/pull/21) and I must have not merged the master template branch correctly at some point to keep those changes around. I believe I've fixed this now.  Let me know if there is anything else.

**Comment by yuchuan2016** [comment]
@lboxell , thanks! One minor issue is the alignment of `mode`  `vers` `sf` and `cache_dir`. Also, should we add instructions on cache/release in the README? Other than that feel free to merge.

**Comment by lboxell** [comment]
Thanks, @yuchuan2016.

I made the changes. I'll merge and close now.

**Pull request merged**
