### PR TITLE
Pull request for gslab_python/#23 Create Lyx scanner 

### PR DESCRIPTION
**Pull request by yuchuan2016**
Hi @lboxell , could you kindly PR this? I think it won't take too much time.

The current scanner can only track implicit dependencies ending with `.lyx` and `.eps` recursively, but it's straightforward to add more extensions.

Please check that modifying the following three implicit dependencies will rebuild the paper without explicitly specifying them as `source`.
- `source/analysis/analysis.do`
- `source/tables/table.lyx`
- `source/figures/figure.lyx`

Do you think it would be better to move these functions to `gslab_scons`? If so, I would move them and make a new release, and specify that the template repo needs the latest version of `gslab_tools`. Or we could for now leave them in `SConstruct`.

### CODE REVIEW

**Comment by lboxell** [comment]
@yuchuan2016,

This is nice. I tested it out by modifying table.lyx and things seemed to work as expected. I think we'll want to store the code in gslab_scons and add a few more extensions, such as .txt and .pdf, (or, perhaps even better, add an option that allows the user to specify what extensions they want to automatically track).

**Comment by yuchuan2016** [comment]
@lboxell , thanks! I think these two lines should live in SConstruct

>lyxScanner = Scanner(lyx_scan, recursive = True)
SourceFileScanner.add_scanner('.lyx', lyxScanner)

There are two options.
- Move `lyx_scan` to `gslab_scons` and add a comprehensive list of extensions like
    `lyx_re =re.compile(r'filename\s(\S+\.(?:lyx|eps|txt|pdf))', re.M)`
- Leave `lyx_scan` in SConstruct, then users can specify the extensions they want to track.

I have not thought of a good way to move `lyx_scan` away and allow users to specify extensions. The `Scanner` needs to take a function as argument.

**Comment by lboxell** [comment]
@yuchuan2016,

What about something like this:

```

def lyx_scan(node, env, path):
    contents = node.get_contents()
    SOURCE = [] 
    for ext in env.EXTENSIONS:
         src_find = re.compile(r'filename\s(\S+\%s' % ext, re.M)
         SOURCE = SOURCE + [source.replace('"', '') for source in src_find.findall(contents)]
    return SOURCE

def lyxScanner(extensions):
    env.EXTENSIONS = extensions  # I think this would modify the global scons env variable (there may be a better way to handle this.
    return Scanner(lyx_scan, recursive = True)

SourceFileScanner.add_scanner('.lyx', lyxScanner(['.eps', '.txt.', '.lyx']))
``` 

I haven't tested this, but it seems like something like this could work, where both function definitions live in gslab_scons.

Let me know what you think.

**Comment by yuchuan2016** [comment]
@lboxell ,

After testing, I think the following way works
Add the function in `gslab_scons`
```
def lyx_scan(node, env, path):
    contents = node.get_contents()
    SOURCE = [] 
    for ext in env.EXTENSIONS:
         src_find = re.compile(r'filename\s(\S+%s)' % ext, re.M)
         SOURCE = SOURCE + [source.replace('"', '') for source in src_find.findall(contents)]
    return SOURCE
```

Add the following two lines in `SConstruct`
```
env.EXTENSIONS = ['.eps', '.txt.', '.lyx']
SourceFileScanner.add_scanner('.lyx', Scanner(lyx_scan, recursive = True))
```
What do you think?

Another thing (not relevant to this thread) is that when I install the latest version of gslab_python 3.0.1, the command `stata_command_unix` and `stata_command_win` would fail.

**Comment by lboxell** [comment]
@yuchuan2016,

I think you can merge this once the updated gslab_python is merged into master.

**Pull request merged**
