### PR TITLE
Pull request for #61: restructure YAML in template 

### PR DESCRIPTION
**Pull request by Shun-Yang**
@stanfordquan , please test it and check if I have achieved our goals listed in #61. Note that you will need to wait for gslab-econ/gslab-python#106 to pull in and switch to the 4.1.0 dev verson of gslab_python.

### CODE REVIEW

**Comment by yuchuan2016** [comment]
Excuse me for my interrupting, but do we have any rule of using 'abc' versus "abc" in a python script? I think we might want to use quotes consistently .

**Comment by stanfordquan** [comment]
@arosenbe and I had a decent debate about it and we settled on consistency within scripts. I'm fine with specifying one over the other. My habit of using double quotes came from Stata.

**Comment by Shun-Yang** [comment]
Good point. I wasn't paying attention on this.  All double quotes work for me.

**Comment by yuchuan2016** [comment]
I think we are using single quotes throughout the current `SConscript` and `SConstruct`, as well as all `gslab_python` scripts. So I would propose we stick to single quotes as default.

**Comment by yuchuan2016** [comment]
@stanfordquan , I can review this if you have not started.

**Comment by yuchuan2016** [comment]
@Shun-Yang , actually I'm not quite sure about why we need a `config_user_template.yaml`.
- We would prompt to users if no `config_user.yaml` is detected in the `load_yaml_value` function [here](https://github.com/gslab-econ/gslab_python/blob/3e7281ee664160e7ecad027abb846f57ba4977aa/gslab_scons/misc.py#L276) and create a `config_user.yaml` automatically.
- We would provide default stata executable in Windows/Unix when no stata executable is specified.
- The cache path and release path in the template do not work almost 100%. 
- If the user does not need stata/release/cache, why do we force them to have such a `config_user.yaml` file to confuse them?

Perhaps I miss something, but I do not see/remember any benefits of this template. Could you remind me of the discussion about this? I would prefer that a `config_user.yaml` is created only if people call it using `load_yaml_value` function.

**Comment by stanfordquan** [comment]
Good point. The default values and prompts given by our `yaml` reader does serve as a "template". Once @Shun-Yang weighed in we may want to ping PIs about this.

**Comment by Shun-Yang** [comment]
@yuchuan2016 , this is indeed good point. I think the config_user_template idea is first raised [here](https://github.com/gslab-econ/template/issues/56#issue-245966052) by Matt. In retrospect, I agree with you that there is really no need on creating such a template as `config_user` will be created anyway if the yaml reader cannot find one. Currently, we only ask users to type in their `Stata executable`. Do we want to also prompt for `cache_dir` and `release_dir` (of course, they can type `none` for all these)? This way, the user at least know that they can set these up via `config_user`.

**Comment by yuchuan2016** [comment]
@Shun-Yang , I think it will prompt to user to enter the release directory if people want to make a release [here](https://github.com/gslab-econ/gslab_python/blob/556a0b79dead081cb0c134600e19b46d0abccb14/gslab_scons/release.py#L35), and it will prompt to users to enter the cache directory if people specify `mode=cache` [here](https://github.com/gslab-econ/template/blob/eaebce91590df81dcd788c9d8eac000f68d8007e/configuration_test.py#L44). 

This question is whether we want the repo to contain a `user-config.yaml` at the beginning regardless of whether it's needed or not, or create such a file when the users need one. I would vote for the second. The first is more likely to cause future breakdown, since after we copy the template, it won't prompt to users to enter the value, but just use the incorrect default value in the template.

**Comment by Shun-Yang** [comment]
Per discussion, we decide that we don't implement this `config_user_template.yaml` for now, as if the user does not have a `config_user.yaml` file, the default is to create a new one with prompt asking user for information.  I confirm that both `stata-executable` and `cache_dir` prompt will properly appear. `release.py` is currently down. A new issue gslab-econ/gslab_python#111 will fix that. 

@gentzkow FYI. Please see discussion in this thread. Let us know if you think there is still need to create `config_user_template.yaml`.

**Comment by Shun-Yang** [comment]
@yuchuan2016 , I have removed `config_user_template`. Let me know if you have other comments on this, or I can pull this in.

**Comment by yuchuan2016** [comment]
@Shun-Yang , great. I have nothing to add. We perhaps want to update the README.md to give instructions on how to turn on the dependencies. But it's up to you whether we want to update it now or update after everything has finished.

**Pull request merged**
