### PR TITLE
Pull request for gslab_python/#57: Fix stata bug in Windows

### PR DESCRIPTION
**Pull request by stanfordquan**
@lboxell please review this change to template to be released alongside gslab_python 4.0.0

I refactored setup.py to fix the bug mentioned in gslab_python/#57. Tested on both Windows and Mac.

### CODE REVIEW

**Comment by lboxell** [comment]
@stanfordquan,

Is the following an issue with not having gslab_python 4.0.0 installed? 

```
siepr-mg-ra-imac-1:template leviboxell$ scons
scons: Reading SConscript files ...
AttributeError: 'module' object has no attribute 'get_stata_executable':
  File "/Users/leviboxell/Desktop/template/SConstruct", line 6:
    [user_configs, mode, sf, cache_dir] = setup_test(ARGUMENTS)
  File "/Users/leviboxell/Desktop/template/setup.py", line 28:
    check_stata(sf)
  File "/Users/leviboxell/Desktop/template/setup.py", line 104:
    stata_exec = misc.get_stata_executable(fake_env)

```

**Comment by stanfordquan** [comment]
Yup, please install gslab_python from the branch `dev_four` which collects changes for the 4.0.0 release

**Comment by lboxell** [comment]
@stanfordquan, 

I get the following when I check things out (seems like an lfs issue):
screen shot 2017-02-27 at 3 20 14 pm

I don't have anything to test on windows stata versions, but it still works on Mac and if you've tested it on Windows, then that should be fine.

**Comment by lboxell** [comment]
@stanfordquan,

The above commit should restore things to using lfs.

**Comment by stanfordquan** [comment]
definitely a git-lfs issue. Must have accidentally committed the repo on windows. Thanks for the commit

**Pull request merged**
