### PR TITLE
Pull request for gslab econ/admin#67:  Complete work on gslab_scons python module 

### PR DESCRIPTION
**Pull request by stanfordquan**
Original [issue here](https://github.com/gslab-econ/admin/issues/67), markdown [here](https://github.com/gslab-econ/admin/blob/issue67/issues/67/admin-67.md). 

As discussed in original comments, this pull request is for code-checking before publishing to PyPI. For that reason, `gslab_scons.py` is still at the top of the directory for now.

@lboxell please PR this, thanks!

### CODE REVIEW

**Comment by lboxell** [comment]
@stanfordquan,

I think you have a good start on this. Here are some comments (feel free to discuss any that aren't clear):

 - Lets keep this line in the readme: `-Individual scripts can be run directly within Stata and R if they are run in order.`
 - Can we have the code run silently when it is looping over Stata flavors and only print the flavor found or an error if no flavor is found at all?
 - Can we move the AddOption portion of the code to gslab_scons.py?
 - Can we have code that checks whether the first item in 'source' is code and print an informative error message if it is not? (E.g., check whether the file has a '.do' extension for build_stata). At a minimum, we should make this explicit in the readme.
 - We probably want to have proper unit tests for the functions in this code before pushing to pypi. And the code should follow the same format as 'gslab_make' and 'gslab_fill'.
 - Does 'platform' return 'win32' for all versions of windows?
 -  Why is `flavor = flavor.replace("stata", "stata-")` necessary? I'm not sure we want the automatic behavior that "stata" is switched with "stata-". What if the executable is just "statamp"? Or if the user specifies "stata-mp"?
 - Also, do we always want to append ".exe" for windows? For example, in our old make.py code, we use `%STATAEXE%` for the stata executable and I'm not sure we would want to append `.exe` if a user enters this. Likewise, do we always want to append '-64'?
 - I think if a user enters a stata executable, we  should make no changes to it with regards to formatting. If no executable is entered, then we can do these modifications to loop through. 
 - In the markdown, I'm confused about the "Low value additions/small annoyances" section. Are these things you fixed or things that are existing issues that need to be addressed?
 - Can we make it a part of the gslab_scons build functions to clean the log file? So we would delete the log_file just before os.system call. 
 - Can we add a print_time() function that prints the date and time and then we print the time into the sconscript.log files right before and after the os.system calls?


(We may want to focus on just getting the functions correct for this task and then focus on the unit tests for the code and pushing to pypi in the next task which would be completed after the sprint.) 

Note: I haven't tested anything on windows yet.

**Comment by stanfordquan** [comment]
@lboxell, my responses are [here](https://github.com/gslab-econ/admin/blob/issue67/issues/67/PRcomments.md).

The tl;dr would be: 
-No unit test yet. All suggested functionalities added and tested on all platforms. More helper functions had to be added.
-build_stata() now makes no effort in formatting user input if provided.

Thanks

**Comment by lboxell** [comment]
@stanfordquan,

These changes look good overall -- the code should be a lot more robust now. A few final comments:

 - I think we want to print the time stamp when the script starts (i.e., `Starting at: [TIME]`) and when it ends (i.e., `Ending at: [TIME]`). It's useful to be able to go back and see how long a specific piece of code took to run.
 - I like the idea of keep the options SConscript within gslab_scons if possible.  

I think you should implement the log timestamp suggestion. Then, create a new task for yourself to move everything to the gslab_scons library with unit tests, the options Sconscript file, and also flag everyone (MG, AR, MS) to review the code before pushing to pypi (per our discussion during that meeting). 

[But don't work on this next task until after the sprint.]

**Comment by lboxell** [comment]
By 'script start', I'm referring to the program calls within the 'SConscript' files, not the SConstruct file.

**Comment by lboxell** [comment]
@stanfordquan,

I assume this is on hold. But just flagging this as being stale (pull requests don't show up alongside issues in our stale issue search).

**Comment by stanfordquan** [comment]
`6df3191` and `bff355a` implemented @lboxell comments. PR on hold.

**Comment by lboxell** [comment]
@stanfordquan,

 - Let's only print the times in the sconscript logs, not the sconstruct log. 
 - If I do `scons --sf=sdfasdf`, everything runs fine with no warning messages or anything. Not sure this is desirable.

**Comment by stanfordquan** [comment]
@lboxell ,

your comments are implemented. 

- time is no longer printed in sconstruct log nor console
- this seems to only be true if stata-related-targets are already built, i.e. if scons is not running build_stata. I think this is in some way desirable, as we do not want to limit what the user want to call as her executable. Let me know if this is not the case.

**Comment by stanfordquan** [comment]
p.s. I edit the way options are solicited similar to your method in large template. Flavour calls are now `scons sf=statase`

**Comment by lboxell** [comment]
Per our discussion,

I'm waiting on the git-lfs issue to be updated here.

**Comment by stanfordquan** [comment]
git lfs issue is resolved, bug is not reproducible, lives in [this commit](https://github.com/gslab-econ/template/pull/7/commits/416c8a12e55443b3d75aebbe12a102b330b6013f)

**Comment by lboxell** [comment]
@stanfordquan,

 Things look good. If you're going to merge this in the next 30 minutes, let me know. Otherwise, I'll do it myself so I can start working on https://github.com/gslab-econ/gslab_python/issues/8

**Pull request merged**
