### PR TITLE
Pull request for #12: Re-implement check_lfs() function

### PR DESCRIPTION
**Pull request by lboxell**

### CODE REVIEW

**Comment by stanfordquan** [comment]
On it!

**Comment by stanfordquan** [comment]
@lboxell , awesome! All good, code works as intended and well written. 

In my first run, I got this error

> template (issue12_checklfs) $ scons
> scons: Reading SConscript files ...
> The filter.lfs.clean attribute should be "git-lfs clean -- %f" but is "git-lfs clean %f"
> Run `git lfs install --force` to reset git config.
> ERROR: Git LFS 1.2 or later is not installed. Please install.

since running the suggested fix made the issue go away (at least for me), I don't think we need to worry about it. Still, it's probably useful to note / understand it if this issue arises again for other users.

**Comment by arosenbe** [comment]
@lboxell I moved my git-lfs binary and tried to run scons. I got the output below. 
```
scons: Reading SConscript files ...
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	last
ERROR: Git LFS 1.2 or later is not installed. Please install.
```

**Comment by arosenbe** [comment]
@lboxell I tried running with version 0.6.0 of git-lfs and scons was still willing to run.
```
scons: Reading SConscript files ...
Error: unknown command "install" for "git-lfs"
Run 'git-lfs --help' for usage.
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
```

**Comment by lboxell** [comment]
Our discussion:

```
try:
  output = git lfs install
else try:
  output = git lfs init
except:
   if grep(output, 'force'):
      please run the on screen command
   else:
      please install git lfs
```

**Comment by lboxell** [comment]
@stanfordquan @arosenbe,

I modified the function similar to what we discussed. I only do one error message, but it should encompass both cases now.

Let me know if there is anything else.

**Comment by arosenbe** [comment]
@lboxell I tried moving my git-lfs binary and still got an ugly error message
```
scons: Reading SConscript files ...
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	last
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	last
ERROR: Either Git LFS is not installed or your Git LFS settings need to be updated. 
                  Please install Git LFS or run 'git lfs install --force' if prompted above.
```

**Comment by arosenbe** [comment]
@lboxell, this new error message is prettier
```
scons: Reading SConscript files ...
/bin/sh: git-lfs: command not found
/bin/sh: git-lfs: command not found
ERROR: Either Git LFS is not installed or your Git LFS settings need to be updated. 
                  Please install Git LFS or run 'git lfs install --force' if prompted above.
```

**Pull request merged**
