### PR TITLE
Pull request for #2: Improve SCons logging

### PR DESCRIPTION
**Pull request by arosenbe**
@lboxell can you please PR? It would be good to check the following 
  *  Both stdout and stderr are written to the log. Note that I do not separate the streams as we will not be using the log file as an input for another program.
  *  I use appropriate syntax to send output to the terminal
  *  I produce the log in the top level and you do not see an obvious way to move the completed log into `output/`.

### CODE REVIEW

**Comment by lboxell** [comment]
@arosenbe,

The only thing I can think of is whether we want to do a solution that will work for both windows and linux. However, I did some searching online and there didn't seem to be a good equivalent built into windows. Maybe you have some other ideas?

**Comment by arosenbe** [comment]
@lboxell, 

This [thread](http://stackoverflow.com/questions/796476/displaying-windows-command-prompt-output-and-redirecting-it-to-a-file/12438402#12438402) suggests that it is impossible to redirect output to the terminal and to a file in Windows. The thread does discuss a way output to a file and then write that file to the command prompt, but this behavior is not ideal and the implementation uses `type` so it will not run Mac.

**Comment by lboxell** [comment]
@arosenbe,

I was thinking we would have a 'start_log()' function (or something like that) in gslab_scons.py that would look something like this:
```
if platform == "[WINDOWS]" (not sure the exact value)
    Do Windows implementation
else if platform == "darwin" or platform == "linux" or platform == "linux2"
    Do what we currently do.
```

**Comment by arosenbe** [comment]
@lboxell After some searching some more, it seems that the only native way to specify within a script that output should be sent to a file and a shell on windows is with a helper function like the one [here](http://stackoverflow.com/questions/11239924/windows-batch-tee-command/21841567#21841567). The solution I was considering [before](https://github.com/gslab-econ/template/pull/4#issuecomment-241864782) only works when calling the script on the command line. I think the logging solution for windows should be tackled in another task, if we decide to implement it.

**Comment by lboxell** [comment]
@arosenbe,

I'm fine leaving it to a different task. At a minimum, we could set it up so that if you're on windows, everything is just outputted to the log  file instead of the console. [Maybe make a note of this on the outline for now.]

Feel free to merge and close. (Then if you have nothing to do tomorrow, you could probably open a new task to implement the windows option.)

**Comment by gentzkow** [comment]
Thanks guys. I'm thinking this is convoluted enough that we should perhaps
drop the idea of logging for Sconscript altogether.

(The value of these logs is limited in any case since they will only record
the last call to scons, not the full set of changes since the previous
revision. So if you run scons, then fix something, then re-run, then
commit, it's only recording the final step.)

Sorry in advance if this means work on this task was wasted effort. Why
don't you (@arosenbe & @lboxell) discuss in the morning and shoot me an
email with your views.

**Comment by arosenbe** [comment]
Per conversation with @lboxell this task can be closed as it accomplishes the task description for mac. Per email with @gentzkow, logging for windows will be implemented in #5.

**Pull request merged**
