### PR TITLE
Pull Request for #66: Force integration with gslab_stata

### PR DESCRIPTION
**Pull request by yuchuan2016**
@Shun-Yang , could you PR this to see if it finishes the goals listed in #66? Thanks!

### CODE REVIEW

**Comment by Shun-Yang** [comment]
@yuchuan2016 , I have tested it and the code works well! Just two minor comments: 
- maybe update the readme in gslab-econ/stata-misc to reflect the changes? 
- maybe add a note in the readme of gslab-econ/template saying that one needs to remove old `preliminaries.ado` if they installed them before?

**Comment by yuchuan2016** [comment]
@Shun-Yang , thanks! I have implemented your comments.

**Comment by stanfordquan** [comment]
@yuchuan2016 would you be able to add instruction on how to delete old GSLab-provided ado files and get the new ado files to work with the current template? We can hide it in a `<details>` tag in the FAQ. I am having a problem figuring it out so it may be difficult for PIs/coauthors.

**Comment by stanfordquan** [comment]
In particular, `preliminaries` is screwing up my `ado` path.

**Comment by stanfordquan** [comment]
Got it. 

```
~ $ stata-mp

  ___  ____  ____  ____  ____ (R)
 /__    /   ____/   /   ____/
___/   /   /___/   /   /___/   14.2   Copyright 1985-2015 StataCorp LLC
  Statistics/Data Analysis            StataCorp
                                      4905 Lakeway Drive
     MP - Parallel Edition            College Station, Texas 77845 USA
                                      800-STATA-PC        http://www.stata.com
                                      979-696-4600        stata@stata.com
                                      979-696-4601 (fax)

Unlimited-user 4-core Stata network license expires 21 Jul 2018:
       Serial number:  501509201134
         Licensed to:  Quan Le
                       Stanford University

Notes:
      1.  Unicode is supported; see help unicode_advice.
      2.  More than 2 billion observations are allowed; see help obs_advice.
      3.  Maximum number of variables is set to 5000; see help set_maxvar.

running /Applications/Stata/profile.do ...

. adopath
  [1]  (BASE)      "/Applications/Stata/ado/base/"
  [2]  (SITE)      "/Applications/ado/"
  [3]              "."
  [4]  (PERSONAL)  "~/Library/Application Support/Stata/ado/personal/"
  [5]  (PLUS)      "~/Library/Application Support/Stata/ado/plus/"
  [6]  (OLDPLACE)  "~/ado/"
```

Then checking the `adopath` for an old version of preliminaries and deleting it works.

**Comment by yuchuan2016** [comment]
@stanfordquan , thanks! I will add instructions on this.

**Pull request merged**
