### PR TITLE
Pull request for #88: Grab all paths when recording inputs

### PR DESCRIPTION
**Pull request by arosenbe**
@stanfordquan, can you review my work from #88. Also see gslab-econ/gslab_python#139. Thanks!

### CODE REVIEW

**Comment by arosenbe** [comment]
Thanks @stanfordquan!

1. Do you mean the SConstruct? If so, no. We call the configuration.py script from the SConstruct, so it only needs to change in one place. If not, I'm not sure that I understand your question.

2. Exactly, paths change but the names of pointers to paths are constant. I could see it going either way in config_global.yaml, but I wanted to write something that would be easily applicable to cofigf_local.yaml.

**Comment by stanfordquan** [comment]
1. It's all good. I did mean the `SConscript` but that's only because I changed the config_global to be one-dimensional, so when I indexed `paths['input']['input']` I get a string indexing error.

**Comment by arosenbe** [comment]
I see, you were talking about the SConscript in analysis/paper_sildes/tables. The commit above takes care of it. 

Now this task is just waiting on the resolution of gslab-econ/gslab_python/#139 to pull.

**Comment by arosenbe** [comment]
PR passed here and at gslab-econ/gslab_python#139. Merging.

**Pull request merged**
