### PR TITLE
Pull request for #10: Updates gslab_scons.py to add gdrive_asset.txt to releases

### PR DESCRIPTION
**Pull request by lboxell**

### CODE REVIEW

**Comment by M-R-Sullivan** [comment]
@lboxell - Nice work here. The release text file gives information that should usually make it clear which files were released and where to find them on Google Drive. A few comments:

- I think that the current lay-out of the textfile is fine, as the metadata does not make it difficult to find the file listing. 

- The Google Drive paths in the `gdrive_assets.txt` assets files are not actually the paths to the files on Google Drive. For instance, this file contained the following line for one of my test releases:
`Google Drive: cache/template/pr11_test2/data.txt`. But wouldn't `release/large_template/pr11_test2/data.txt` be the correct path? Also, is there any reason for printing "Google Drive: " in front of each path instead of just once at the top?

- A gdrive_assets.txt file listing the `DriveReleaseFiles` is included with GitHub releases even if there is no release to Google Drive.  I suspect that this is not desirable, though you can correct me if I'm mistaken.

- To make some minor code style suggestions, I think the `Release()` function could be improved by making some of the long lines shorter and by giving the variables `j`, `a`, `A`, and `s` more descriptive names.

**Comment by lboxell** [comment]
@M-R-Sullivan,

I implemented all of your comments. As part of this, I set scons up so that we don't have to type 'drive' when we want to release assets to google drive, which I think is an improvement. We just specify them in 'DriveReleaseFiles'. 

Let me know if there is anything else.

**Comment by M-R-Sullivan** [comment]
@lboxell - Great. I agree with your decision to scrap the `drive` option. 

One last thing, though: I am still getting `template` instead of `large_template` in the path. Perhaps rather than feeding the repo to the Release() function, the function could recover the repo's release directory on Google Drive from `local_release`?

**Comment by lboxell** [comment]
@M-R-Sullivan, 

Good point and good suggestion. I implemented your proposal. Let me know if there is anything else.

**Comment by M-R-Sullivan** [comment]
@lboxell - The change looks good. Feel free to close!

**Pull request merged**
